
import React, { useState } from 'react';
import { QuizQuestion } from '../types';

interface QuizViewProps {
  quiz: QuizQuestion[];
}

const QuizView: React.FC<QuizViewProps> = ({ quiz }) => {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [selectedOption, setSelectedOption] = useState<number | null>(null);
  const [isAnswered, setIsAnswered] = useState(false);
  const [score, setScore] = useState(0);
  const [isFinished, setIsFinished] = useState(false);

  // Validate input is an array
  if (!quiz || !Array.isArray(quiz) || quiz.length === 0) {
    return (
      <div className="text-center p-12 border-2 border-dashed border-border rounded-3xl">
        <p className="text-text-muted italic">No quiz data available.</p>
      </div>
    );
  }

  const handleOptionSelect = (idx: number) => {
    if (isAnswered) return;
    setSelectedOption(idx);
  };

  const handleCheckAnswer = () => {
    if (selectedOption === null) return;
    if (selectedOption === quiz[currentIndex].correctAnswer) {
      setScore(score + 1);
    }
    setIsAnswered(true);
  };

  const handleNext = () => {
    if (currentIndex + 1 < quiz.length) {
      setCurrentIndex(currentIndex + 1);
      setSelectedOption(null);
      setIsAnswered(false);
    } else {
      setIsFinished(true);
    }
  };

  const handleDownload = () => {
    const content = quiz.map((q, i) => 
      `Q${i+1}: ${q.question}\n` + 
      q.options.map((opt, oi) => `  ${String.fromCharCode(65+oi)}) ${opt}`).join('\n') +
      `\nCorrect: ${String.fromCharCode(65+q.correctAnswer)}\nExplanation: ${q.explanation}\n\n`
    ).join('-------------------\n');
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'study_quiz.txt';
    a.click();
  };

  const handleExportPDF = () => {
    window.print();
  };

  // PRINT VIEW RENDERER
  const renderPrintView = () => (
    <div className="print-only">
      <div className="mb-8 border-b-2 border-black pb-4">
        <h1 className="text-3xl font-black text-black">Mastery Quiz</h1>
        <p className="text-sm text-gray-500">Generated by StudyEasierAI</p>
      </div>
      <div className="space-y-8">
        {quiz.map((q, i) => (
          <div key={i} className="break-inside-avoid">
            <h3 className="text-lg font-bold text-black mb-2">{i + 1}. {q.question}</h3>
            <ul className="pl-5 space-y-1 mb-3">
              {q.options.map((opt, idx) => (
                <li key={idx} className="list-alpha text-gray-800 text-sm">
                   <span className="font-bold mr-2">{String.fromCharCode(65 + idx)})</span> {opt}
                </li>
              ))}
            </ul>
            <div className="mt-2 p-3 bg-gray-50 border border-gray-200 rounded text-sm">
              <p className="font-bold text-black">Answer: {String.fromCharCode(65 + q.correctAnswer)}</p>
              <p className="text-gray-600 italic mt-1">{q.explanation}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );

  const q = quiz[currentIndex];
  if (!q) return null;

  return (
    <div className="max-w-2xl mx-auto py-8 px-4 animate-fadeIn">
      {renderPrintView()}
      
      {/* WEB INTERACTIVE VIEW (Hidden on Print) */}
      <div className="no-print">
        {isFinished ? (
          <div className="text-center py-16 px-8 bg-surface rounded-3xl border border-border shadow-2xl animate-fadeIn">
            <div className="mb-8 inline-flex items-center justify-center w-24 h-24 bg-amber-600/20 text-amber-400 rounded-3xl shadow-xl shadow-amber-600/10 rotate-3">
              <i className="fas fa-award text-4xl"></i>
            </div>
            <h2 className="text-3xl font-black text-text-main mb-2">Mastery Complete!</h2>
            <p className="text-text-muted mb-8 text-lg">
              Accuracy: <span className="text-emerald-400 font-black">{Math.round((score / quiz.length) * 100)}%</span> ({score}/{quiz.length})
            </p>
            
            <div className="h-2 w-full bg-surface2 rounded-full mb-10 overflow-hidden border border-border">
              <div 
                style={{ width: `${Math.round((score / quiz.length) * 100)}%` }} 
                className="h-full bg-gradient-to-r from-emerald-500 to-emerald-400 transition-all duration-1000 ease-out"
              />
            </div>

            <div className="flex gap-4">
              <button
                onClick={() => {
                  setCurrentIndex(0);
                  setSelectedOption(null);
                  setIsAnswered(false);
                  setScore(0);
                  setIsFinished(false);
                }}
                className="flex-1 py-4 bg-emerald-600 text-white rounded-2xl font-black hover:bg-emerald-700 transition-all shadow-lg shadow-emerald-600/20 uppercase tracking-widest text-xs"
              >
                Retake Mastery
              </button>
              <button
                onClick={handleDownload}
                className="py-4 px-6 bg-surface2 text-text-main rounded-2xl font-black hover:bg-surface transition-all uppercase tracking-widest text-xs border border-border"
                title="Download TXT"
              >
                <i className="fas fa-file-alt"></i>
              </button>
              <button
                onClick={handleExportPDF}
                className="py-4 px-6 bg-amber-600 text-white rounded-2xl font-black hover:bg-amber-700 transition-all uppercase tracking-widest text-xs border border-amber-500 shadow-lg shadow-amber-600/20"
                title="Export PDF"
              >
                <i className="fas fa-file-pdf"></i>
              </button>
            </div>
          </div>
        ) : (
          <>
            <div className="flex items-center justify-between mb-8">
              <span className="text-[10px] font-black text-emerald-500 bg-emerald-500/10 px-4 py-2 rounded-xl uppercase tracking-[0.2em] border border-emerald-500/20">
                Knowledge Check {currentIndex + 1} / {quiz.length}
              </span>
              <div className="flex items-center gap-4">
                <span className="text-xs font-bold text-text-muted uppercase tracking-widest">
                  Score: {score}
                </span>
                <button 
                  onClick={handleExportPDF}
                  className="text-text-muted hover:text-text-main transition-colors"
                  title="Print Quiz"
                >
                  <i className="fas fa-print"></i>
                </button>
              </div>
            </div>

            <div className="bg-surface rounded-3xl border border-border p-10 mb-8 shadow-xl">
              <h3 className="text-xl font-bold text-text-main mb-10 leading-relaxed">{q.question}</h3>
              
              <div className="space-y-4">
                {q.options.map((option, idx) => {
                  let style = 'bg-surface2 border-border text-text-muted hover:border-text-muted';
                  
                  if (isAnswered) {
                    if (idx === q.correctAnswer) {
                      style = 'bg-emerald-600/10 border-emerald-500 text-emerald-400';
                    } else if (idx === selectedOption) {
                      style = 'bg-rose-600/10 border-rose-500 text-rose-400 opacity-80';
                    } else {
                      style = 'bg-surface2 border-border text-text-muted opacity-50';
                    }
                  } else if (idx === selectedOption) {
                    style = 'bg-emerald-600/5 border-emerald-500 text-text-main shadow-lg shadow-emerald-500/10';
                  }

                  return (
                    <button
                      key={idx}
                      disabled={isAnswered}
                      onClick={() => handleOptionSelect(idx)}
                      className={`w-full text-left p-5 rounded-2xl border-2 transition-all flex items-center gap-5 ${style}`}
                    >
                      <span className={`w-10 h-10 flex items-center justify-center rounded-xl border text-sm font-black shrink-0 ${
                        idx === selectedOption ? 'bg-emerald-500 text-white border-emerald-500' : 'bg-surface border-border text-text-muted'
                      }`}>
                        {String.fromCharCode(65 + idx)}
                      </span>
                      <span className="font-bold text-sm">{option}</span>
                      {isAnswered && idx === q.correctAnswer && <i className="fas fa-check-circle text-emerald-500 ml-auto"></i>}
                      {isAnswered && idx === selectedOption && idx !== q.correctAnswer && <i className="fas fa-times-circle text-rose-500 ml-auto"></i>}
                    </button>
                  );
                })}
              </div>
            </div>

            {isAnswered && (
              <div className="bg-emerald-600/5 rounded-2xl p-6 mb-8 border border-emerald-500/10 animate-fadeIn">
                <h4 className="text-[10px] font-black text-emerald-500 uppercase tracking-widest mb-2 flex items-center gap-2">
                  <i className="fas fa-lightbulb"></i> Smart Insight
                </h4>
                <p className="text-text-muted text-xs leading-relaxed italic">{q.explanation}</p>
              </div>
            )}

            <div className="flex gap-4">
              {!isAnswered ? (
                <button
                  onClick={handleCheckAnswer}
                  disabled={selectedOption === null}
                  className={`flex-1 py-5 rounded-2xl font-black transition-all uppercase tracking-widest text-xs ${
                    selectedOption !== null 
                    ? 'bg-emerald-600 text-white hover:bg-emerald-700 shadow-xl shadow-emerald-600/20' 
                    : 'bg-surface2 text-text-muted cursor-not-allowed border border-border'
                  }`}
                >
                  Submit Answer
                </button>
              ) : (
                <button
                  onClick={handleNext}
                  className="flex-1 py-5 bg-emerald-600 text-white rounded-2xl font-black hover:bg-emerald-700 transition-all shadow-xl shadow-emerald-600/20 uppercase tracking-widest text-xs"
                >
                  {currentIndex + 1 < quiz.length ? 'Next Module' : 'Finish Mastery Check'}
                </button>
              )}
            </div>
          </>
        )}
      </div>
    </div>
  );
};

export default QuizView;
